version: 2
jobs:
    build:
        docker:
            - image: circleci/buildpack-deps
        steps:
            - checkout
            - setup_remote_docker
            - run:
                  name: "Build alpine image"
                  command: |
                      docker login -u ${DOCKER_HUB_USER_ID} -p ${DOCKER_HUB_PWD}
