version: 2
jobs:
    build_alpine:
        filters:
            tags:
                only: /.*/
        docker:
              - image: circleci/buildpack-deps
        resource_class: small
        steps:
            - checkout
            - setup_remote_docker
            -   run:
                    name: 'Build alpine image'
                    command: |
                        docker login -u $DOCKER_HUB_USER_ID -p $DOCKER_HUB_PWD
                        docker build . --rm --tag $DOCKER_HUB_USER_ID/rsync:alpine-$CIRCLE_BRANCH --tag $DOCKER_HUB_USER_ID/rsync:alpine-latest -f alpine/Dockerfile
            -   run:
                    name: 'Publish alpine image'
                    command: |
                        docker push $DOCKER_HUB_USER_ID/rsync:alpine-$CIRCLE_BRANCH
                        docker push $DOCKER_HUB_USER_ID/rsync:alpine-latest

    build_debian:
        filters:
            tags:
                only: /.*/
        docker:
            -   image: circleci/buildpack-deps
        resource_class: small
        steps:
            - checkout
            - setup_remote_docker
            -   run:
                    name: 'Build debian image'
                    command: |
                        docker login -u $DOCKER_HUB_USER_ID -p $DOCKER_HUB_PWD
                        docker build . --rm --tag $DOCKER_HUB_USER_ID/rsync:debian-$CIRCLE_BRANCH --tag $DOCKER_HUB_USER_ID/rsync:debian-latest -f debian/Dockerfile

            -   run:
                    name: 'Publish debian image'
                    command: |
                        docker push $DOCKER_HUB_USER_ID/rsync:debian-$CIRCLE_BRANCH
                        docker push $DOCKER_HUB_USER_ID/rsync:debian-latest

    build_centos:
        filters:
            tags:
                only: /.*/
        docker:
            -   image: circleci/buildpack-deps
        resource_class: small
        steps:
            - checkout
            - setup_remote_docker
            -   run:
                    name: 'Build centos image'
                    command: |
                        docker login -u $DOCKER_HUB_USER_ID -p $DOCKER_HUB_PWD
                        docker build . --rm --tag $DOCKER_HUB_USER_ID/rsync:centos-$CIRCLE_BRANCH --tag $DOCKER_HUB_USER_ID/rsync:centos-latest -f debian/Dockerfile
            -   run:
                    name: 'Publish centos image'
                    command: |
                        docker push $DOCKER_HUB_USER_ID/rsync:centos-$CIRCLE_BRANCH
                        docker push $DOCKER_HUB_USER_ID/rsync:centos-latest
